- README.md
- cmd/root/root.go
- internal/config/config.go
- internal/sessiontoken/sessiontoken.go
This change allows the user to set the expiration time for the AWS credentials retrieved by `okta-aws-cli`.
> Add argument/env var to set the session expiry for the AWS credentials.

- README.md
- cmd/root/root.go
- internal/config/config.go
- internal/output/aws_credentials_file.go
- internal/output/envvar.go
* Document need for `AWS_REGION` env variable if AWS IdP is in a non-commercial AWS region.
* If configured with an org domain in admin form, warn and proactively update the value.
* Correctly write creds file when `AWS_CREDENTIALS` is set.
* Document `aws-iam-idp` and `aws-iam-role` are intended as preset to the idp and roles list presented to the user.
* `AWS_PROFILE` is unnecessary in env var output.
* Illustrate `make tools` is used to install the tools the Makefile makes use of.
> Clean up smalls

- internal/sessiontoken/sessiontoken.go
As is, if there is a problem with the auth flow, it's not obvious what the issue might be beyond a generic "400" error response. In our case the swallowed error was:
{"error":"invalid_grant","error_description":"The application's assurance requirements are not met by the 'subject_token'."}
This just adds that to the output.
This also does a small restructure to make sure we're closing the response body per golang guidelines.
> This change adds the response body output when an error occurs. 

- README.md
- cmd/root/root.go
- go.mod
- go.sum
- internal/aws/aws.go
- internal/config/config.go
- internal/output/aws_credentials_file.go
- internal/output/aws_credentials_file_test.go
- Bringing in @ctennis's #26 
- Gates writing/update instead of only appending AWS creds file with CLI flag `--write-aws-credentials`
- Unit test so we can easily see how much the INI package modifies a sloppily formatted creds file.
> Write aws creds file

- internal/config/config.go
Write aws creds flag implies aws-credentials format and shouldn't have to be set explicitly.
Closes #39
> `--write-aws-credentials` implies format `aws-credentials`

- README.md
- cmd/root/root.go
- internal/config/config.go
- internal/config/net.go
- internal/sessiontoken/sessiontoken.go
Use golang httputil to verbosely print all API calls and response including urls, headers, bodies to screen.
> pretty print http debug with  httputil

- README.md
- internal/output/envvar.go
When on Windows `setx` instead of `export`.
Closes #48
> Windows `setx`

- internal/sessiontoken/sessiontoken.go
When using multiple fed apps AND those apps are making use of "Role Value Pattern" for establishing the IdP ARN for the fed app. Tthe IdP ARN value will not be known during list apps (which is used to list apps in the ncurses menu). Instead, each app needs to be retrieved directly from the API (after initial listing) as its IdP ARN value is determined at that time by the Okta service.
> Fix setting/getting IDP ARN value when Role Value Pattern is used on AWS Federation App

- internal/sessiontoken/sessiontoken.go
As is when running the aws cli and an error is returned during the `fetchWebSSO()` call only the http error code is returned,
`Error: fetching SSO web token received API response "400 Bad Request"`
Update the function to check if an error is returned and if so add it to the error message to be displayed,
Incorrectly configured app in Web SSO field of the AWS Federation Application now returns,
```
Open the following URL to begin Okta device authorization for the AWS CLI
https://emanor-oie.oktapreview.com/activate?user_code=VQPWSLVD
Error: fetching SSO web token received API response "400 Bad Request"
error: "invalid_grant", description: "The target audience app must be configured to allow the client to request a 'web_sso_token'."
```
If the AWS Federation App has a more restrictive …
> Return underlying Error if present in fetchWebSSO()

- CHANGELOG.md
- internal/config/config.go
- internal/sessiontoken/sessiontoken.go
* `setx` output when in Windows environment [#49](https://github.com/okta/okta-aws-cli/pull/49), thanks [@monde](https://github.com/monde)!
* `--write-aws-credentials` implies output format `aws-credentials` [#40](https://github.com/okta/okta-aws-cli/pull/40), thanks [@monde](https://github.com/monde)!
* Verbose HTTP API call/resonse logging with `--debug-api-calls` flag [#43](https://github.com/okta/okta-aws-cli/pull/43), thanks [@monde](https://github.com/monde)!
* Return underlying Error if present in fetchWebSSO() [#47](https://github.com/okta/okta-aws-cli/pull/47), thanks [@emanor-okta](https://github.com/emanor-okta)!
* Fix setting/getting IDP ARN value when Role Value Pattern is used on AWS Federation App [#51](https://github.com/okta/okta-aws-cli/pull/51), thanks …
> prep v0.2.0 release

- go.mod
- go.sum
- Update golang/text dependency from 0.3.7 to 0.7.0 (latest)
- Fix OKTA-554144
> Update golang/text dependency

- cmd/root/root.go
*(I believe this is an "obvious fix" so I did not sign the [CLA](https://developer.okta.com/cla/).)*
This removes an extra colon after `Usage:` in the following output:
```
$ okta-aws-cli --help
okta-aws-cli - Okta federated identity for AWS CLI
Okta authentication for federated identity providers in support of AWS CLI.
okta-aws-cli handles authentication to the IdP and token exchange with AWS STS
to collect a proper IAM role for the AWS CLI operator.
Usage::
okta-aws-cli [flags]
Flags:
-a, --aws-acct-fed-app-id string   AWS Account Federation app ID
-w, --aws-credentials string       Path to AWS credentials file, only valid with format "aws-credentials" (default "/home/linuxbrew/.aws/credentials")
-i, --aws-iam-idp string           Preset IAM Identity Provider ARN
-r, --aws-iam-role …
```
> Remove an extra colon in usage text

- README.md
- cmd/root/root.go
- internal/aws/aws.go
- internal/config/config.go
- internal/output/aws_credentials_file.go
- internal/output/aws_credentials_file_test.go
- internal/output/envvar.go
- internal/sessiontoken/sessiontoken.go
okta-aws-cli writes AWS creds variables in session token orientation as `aws_session_token`, `aws_access_key_id`,`aws_secret_access_key`.  This is done for the given profile of an INI file when running in write aws creds mode. Other tools may still be setting obsolete AWS creds variables ([AWS deprecated `aws_security_token` in November 2014, it is not referred to any any public AWS CLI documentation](https://github.com/aws/aws-cli/commit/ff5987ebc6c852fcfcf8c975847ee9185de1610d)) that conflict with modern usage. Therefore, instead of ignoring or destroying previous unnecessary values just comment them out so `$ aws [op] [args]` executes without error.
Given aws creds
```
[default]
random                = thing
aws_session_token     = abc
aws_access_key_id     = def
aws_secret_access_key …
```
> AWS profiles in creds INI file w/ deprecated variables

- internal/config/config.go
Correctly set session duration from AWS_SESSION_DURATION env var
Closes #67
> Correctly set session duration from AWS_SESSION_DURATION env var

- internal/config/config.go
Try to help the operator if they are using a URL format value for org
domain when all we need is the hostname.
Closes #44
> Try to help the operator if they are using a URL format value for org

- README.md
- cmd/root/root.go
Promote AWS_REGION from .env if it exists for proper AWS API behavior.
Closes #45
> Promote AWS_REGION from .env if it exists for proper AWS API behavior.

- internal/sessiontoken/sessiontoken.go
Pre-flight check if org is Classic or OIE
Closes #60
> Pre-flight check if org is Classic or OIE

- CHANGELOG.md
- README.md
- internal/config/config.go
* Remove an extra colon in usage text [#76](https://github.com/okta/okta-aws-cli/pull/76), thanks [@ZhongRuoyu](https://github.com/ZhongRuoyu)!
* Deal with deprecated/obsolete/unsupported `aws_security_token` variable [#79](https://github.com/okta/okta-aws-cli/pull/79), thanks [@monde](https://github.com/monde)!
* added proxy support to http client [#80](https://github.com/okta/okta-aws-cli/pull/80), thanks [@SaltyPeaches](https://github.com/SaltyPeaches)!
* Try to help the operator if they are using a URL format value for org [#82](https://github.com/okta/okta-aws-cli/pull/82), thanks [@monde](https://github.com/monde)!
* Pre-flight check if org is Classic or OIE [#84](https://github.com/okta/okta-aws-cli/pull/84), thanks [@monde](https://github.com/monde)!
* Promote AWS_REGION from .env …
> preparing v0.3.0 release

- internal/config/config.go
- internal/config/errors.go
- internal/output/aws_credentials_file.go
- internal/sessiontoken/sessiontoken.go
Best practices code, switching config over to query object/method style of behavior. Let the config tell us its state, don't make decisions about state outside of the config.
> refactor config

- internal/sessiontoken/sessiontoken.go
This way any output the browser command might print won't cause issues when running `eval $(okta-aws-cli)`.
This aims to resolve #91
> Send browser command stdout to stderr

- README.md
- cmd/root/root.go
- go.mod
- go.sum
- internal/aws/aws.go
- internal/config/config.go
- internal/output/aws_credentials_file.go
- internal/output/aws_credentials_file_test.go
- internal/sessiontoken/sessiontoken.go
Bringing in @tim-fitzgerald's work from #56. Writing
`x_security_token_expires` to AWS creds file is gated by a CLI flag
`--expiry-aws-variables`
> Bringing in @tim-fitzgerald's PR 56 `x_security_token_expires` value

- CHANGELOG.md
- README.md
- internal/config/config.go
* Cache Okta API access token [#100](https://github.com/okta/okta-aws-cli/pull/100), thanks [@monde](https://github.com/monde)!
* Bringing in @tim-fitzgerald's PR #56 `x_security_token_expires` value [#56](https://github.com/okta/okta-aws-cli/pull/56) [#99](https://github.com/okta/okta-aws-cli/pull/99), thanks [@tim-fitzgerald](https://github.com/tim-fitzgerald)!
* Prepend OKTA_AWSCLI_ on ENV VARs [#98](https://github.com/okta/okta-aws-cli/pull/98), thanks [@monde](https://github.com/monde)!
* Config for IdP menu [#97](https://github.com/okta/okta-aws-cli/pull/97), thanks [@monde](https://github.com/monde)!
* Send browser command stdout to stderr [#93](https://github.com/okta/okta-aws-cli/pull/93), thanks [@daniel-sampliner](https://github.com/daniel-sampliner)!
* Refactor config …
> v1.0.0 release

- CHANGELOG.md
- README.md
- cmd/root/root.go
- internal/config/config.go
- internal/sessiontoken/sessiontoken.go
* Print out operational debugging information flag [#113](https://github.com/okta/okta-aws-cli/pull/113), thanks [@monde](https://github.com/monde)!
> --debug flag and release candidate

- CHANGELOG.md
- README.md
- internal/config/config.go
- internal/sessiontoken/sessiontoken.go
Friendly IdP and Role labels don't also print out ARN value (less text clutter in the UI)
Example:
```
$ otka-aws-cli
System web browser will open the following URL to begin Okta device authorization for the AWS CLI
https://example.okta.com/activate?user_code=ZJVFJZNT
? Choose an IdP:  [Use arrows to move, type to filter]
> S3 IdP
EC2 IdP
EKS IdP
CloudFront IdP
```
> Refine friendly IdP and Role label

- CHANGELOG.md
- internal/config/config.go
* Ensure evaluation of CLI flag for profile is in the same order as the other flags [#124](https://github.com/okta/okta-aws-cli/pull/124)
* Retry cached access token if it isn't expired by but receives API error [#127](https://github.com/okta/okta-aws-cli/pull/127)
> preparing 1.2.2 release

- CHANGELOG.md
- README.md
- cmd/root/root.go
- internal/aws/aws.go
- internal/aws/aws_test.go
- internal/config/config.go
- internal/exec/exec.go
- internal/m2mauth/m2mauth.go
- internal/output/aws_credentials_file.go
- internal/output/envvar.go
- internal/output/noop.go
- internal/output/output.go
- internal/output/process_credentials.go
- internal/output/process_credentials_test.go
- internal/utils/utils.go
- internal/webssoauth/webssoauth.go
Add `--exec` subcommand to avoid writing credentials to disk or injectinginto the shell
Closes #135
Example 1
```
$ okta-aws-cli m2m --format noop --exec -- printenv
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=ASIAUJHVCS6UYRTRTSQE
AWS_SECRET_ACCESS_KEY=TmvLOM/doSWfmIMK...
AWS_SESSION_TOKEN=FwoGZXIvYXdzEF8aDKrf...
```
Example 2
```
$ okta-aws-cli m2m --format noop --exec -- aws s3 ls s3://example
PRE aaa/
2023-03-08 16:01:01          4 a.log
```
Example 3 (process had error and also writes to STDERR)
```
$ okta-aws-cli m2m --format noop --exec -- aws s3 mb s3://no-access-example
error running process
aws s3 mb s3://yz-nomad-og
make_bucket failed: s3://no-access-example An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied
Error: exit status 1
```
> `--exec` subcommand

- CHANGELOG.md
- README.md
- cmd/root/web/web.go
- internal/aws/aws.go
- internal/config/config.go
- internal/exec/exec.go
- internal/m2mauth/m2mauth.go
- internal/output/aws_credentials_file.go
- internal/output/aws_credentials_file_test.go
- internal/output/envvar.go
- internal/output/noop.go
- internal/output/output.go
- internal/output/process_credentials.go
- internal/utils/utils.go
- internal/webssoauth/webssoauth.go
Based on @daniel-sampliner`s work in #94
`okta-aws-cli` will collect all available AWS IAM Roles for a given Okta AWS
Federation app (IdP) at once.  This is a feature specific to writing the
`$HOME/.aws/credentials` file. Roles will be AWS account alias name (if STS list
aliases is available on the given role) then `-` then abbreviated role name.
```
$ okta-aws-cli web \
--org-domain test.okta.com \
--oidc-client-id 0oa5wyqjk6Wm148fE1d7 \
--write-aws-credentials \
--all-profiles
? Choose an IdP: AWS Account Federation
Updated profile "myorg-S3-read" in credentials file "/Users/me/.aws/credentials".
Updated profile "myorg-S3-write" in credentials file "/Users/me/.aws/credentials".
```
> web command - collect all roles for an AWS Fed App (idp) at once

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
- README.md
- cmd/root/web/web.go
- go.mod
- go.sum
- internal/aws/aws.go
- internal/config/config.go
- internal/output/aws_credentials_file.go
- internal/output/envvar.go
- internal/output/noop.go
- internal/output/output.go
- internal/output/process_credentials.go
- internal/webssoauth/webssoauth.go
- internal/webssoauth/webssoauth_test.go
The `web` command will open the system's default web browser when the
`--open-browser` flag is present. It is convenient to have the browser open on a
separate profile. If the command to open the browser is known for the host
system an alternate open command can be specified.
```
$ okta-aws-cli web \
--org-domain test.okta.com \
--oidc-client-id 0oa5wyqjk6Wm148fE1d7 \
--open-browser-command "open -na \"Google\ Chrome\" --args --incognito"
```
```
$ okta-aws-cli web \
--org-domain test.okta.com \
--oidc-client-id 0oa5wyqjk6Wm148fE1d7 \
--open-browser-command "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --profile-directory=\"Profile\ 1\""
```
> Alternate open browser command

- CHANGELOG.md
- README.md
- internal/config/config.go
- internal/webssoauth/webssoauth.go
- internal/webssoauth/webssoauth_test.go
Friendly label matching for IdPs and Roles with `$HOME/.okta/okta.yaml` file can
be regular expressions.
Example: your organization uses the same role naming convention across many
different AWS accounts:
```yaml
---
awscli:
idps:
"arn:aws:iam::123456789012:saml-provider/company-okta-idp": "Data Production"
"arn:aws:iam::012345678901:saml-provider/company-okta-idp": "Data Development"
"arn:aws:iam::901234567890:saml-provider/company-okta-idp": "Marketing Production"
"arn:aws:iam::890123456789:saml-provider/company-okta-idp": "Marketing Development"
roles:
"arn:aws:iam::.*:role/admin": "Admin"
"arn:aws:iam::.*:role/operator": "Ops"
```
```
? Choose an IdP:  
> Data Production
Data Development
Marketing Production
Marketing Development
? Choose a Role:  [Use arrows to move, type to filter] …
```
> wildcard friendly labels

- cmd/root/root.go
This fixes a regression in the v2.0 series where `okta-aws-cli --version` (and `okta-aws-cli -v`) doesn't work.
Expected:
```
okta-aws-cli version 2.0.0-beta.5
```
Actual:
```
Error: unknown flag: --version
Usage:
okta-aws-cli web [flags]
```
I tested with the `2.0.0-beta.5` binary on linux/amd64.
> fix(cli): allow running --version without a subcommand

- CHANGELOG.md
- README.md
- cmd/root/m2m/m2m.go
- cmd/root/web/web.go
- internal/config/config.go
- internal/flag/flag.go
- internal/m2mauth/m2mauth.go
- internal/webssoauth/webssoauth.go
* New m2m flag `--private-key-file` read private key from file
* Bug fix panic when okta.yaml is not established (it doesn't have to be established either)
* Bug fix allowing `--version` w/o sub command [#150](https://github.com/okta/okta-aws-cli/pull/150), thanks [@malept](https://github.com/malept)!
> prep v2.0.0-beta.6

- .goreleaser.yaml
- CHANGELOG.md
- internal/config/config.go
* Packaged binary's don't have postfix version value on file name [#154](https://github.com/okta/okta-aws-cli/pull/154)
* Binaries produced by golang for Windows amd64 runtimes are triggering AVs so we will not publish this for the OS/Arch [#166](https://github.com/okta/okta-aws-cli/pull/166)
* CLI version incorrectly rev'd on previous release [#164](https://github.com/okta/okta-aws-cli/pull/164)
> Prep v2.0.1 Release

- CHANGELOG.md
- internal/config/config.go
- internal/output/aws_credentials_file.go
- internal/output/output.go
Process credentials format was not emitting JSON correctly when `--write-aws-credentials` flag is present.
Closes #169
> Fix rocess credentials format bug when `--write-aws-credentials` flag is present.

- CHANGELOG.md
- README.md
- cmd/root/root.go
- internal/aws/aws.go
- internal/config/config.go
- internal/m2mauth/m2mauth.go
- internal/output/aws_credentials_file.go
- internal/output/aws_credentials_file_test.go
- internal/utils/utils.go
- internal/webssoauth/webssoauth.go
Adds AWS Region as a CLI flag for explicitly setting that value.
Closes #160
Closes #161
> AWS Region CLI flag `--aws-region`

- internal/webssoauth/webssoauth.go
`--aws-iam-idp` and `--aws-iam-role` values can be friendly label and we'll reverse look up the ARN value for them from okta.yaml.
Closes #102
Given an okta.yaml of
```
---
awscli:
idps:
"arn:aws:iam::123:saml-provider/S3_IDP": "S3 IdP"
"arn:aws:iam::123:saml-provider/EC2_IDP": "EC2 IdP"
roles:
"arn:aws:iam::123:role/S3_RW": "S3 Read/Write"
"arn:aws:iam::123:role/S3_READ": "OK S3 Read"
"arn:aws:iam::123:role/EC2_full_access": "EC2 FULL"
```
`okta-aws-cli` can be invoked with ARN or friendly label values:
```
$  okta-aws-cli web --oidc-client-id 0oabc --org-domain test.okta.com \
--aws-iam-idp arn:aws:iam::123:saml-provider/S3_IDP \
--aws-iam-role arn:aws:iam::123:role/S3_READ
$  okta-aws-cli  web --oidc-client-id 0oabc --org-domain test.okta.com \
--aws-iam-idp "S3 IdP" \
--aws-iam-role …
```
> `--aws-iam-idp` and `--aws-iam-role` alias values

- CHANGELOG.md
- internal/config/config.go
* Multiple okta-aws-cli configurations in `okta.yaml` by AWS profile name.
[#162](https://github.com/okta/okta-aws-cli/pull/162), thanks [@MatthewJohn](https://github.com/MatthewJohn)!
* Explicitly set AWS Region with CLI flag `--aws-region` [#174](https://github.com/okta/okta-aws-cli/pull/174), thanks [@euchen-circle](https://github.com/euchen-circle), [@igaskin](https://github.com/igaskin)!
* `--aws-iam-idp` and `--aws-iam-role` arguments can be ARN or friendly label [#178](https://github.com/okta/okta-aws-cli/pull/178), thanks [@monde](https://github.com/monde)!
* Fix bug where all flags were not being set on the config object. [#177](https://github.com/okta/okta-aws-cli/pull/177), thanks [@monde](https://github.com/monde)!
* Process credentials format was not emitting JSON correctly …
> v2.1.0 release

- README.md
Improve explanation of default commands. Explicitly list required arguments in README examples.
Closes #183
> Improve explanation of default commands.

- CHANGELOG.md
- internal/config/config.go
Fix default values in config when using AWS profile argument using AWS profiles in Okta config.
Fix logic that determines if the AWS-profile-specific config key has been set - viper InConfig and IsSet appear to always return true, even if the value is not defined in the "profile.key"
Fixes https://github.com/okta/okta-aws-cli/issues/182
Profile value is already set, remove unnecessary function call.
Closes #187 
Closes #182
> MatthewJohn's PR 187

- internal/config/config.go
`viper.Get()` returns an empty string when an AWS profile exists in the config, but has not been set.
`viper.Get()` returns nil when the AWS profile does not exist in the config or the config file does not exist. viper.
`viper.IsSet()` returns will return false when the config/profile does not exist, but always returns true when the profile exists (irrelevant of whether the actual key is defined).
Combining these two means that:
* When a config file does not exist or profile is not present in the config, IsSet will return false and the original key is returned.
* When a config file does exist and the profile exists, but the config key does not exist, Get will return an empty string and the key is returned.
* When a config file does exist, the profile exists and the key exists, IsSet …
> Fix command line arguments and non-AWS profile scoped arguments when an AWS profile is not present in the config.

- CHANGELOG.md
- internal/config/config.go
* Additional fix for bug dealing with multiple profiles in okta.yaml [#196](https://github.com/okta/okta-aws-cli/pull/196), thanks [@MatthewJohn](https://github.com/MatthewJohn)!
Closes #192
Closes #193
Closes #194
> v2.1.2 release

- cmd/root/root.go
In the list of arguments in the README.md for `okta-aws-cli` it is written:
Name | Description | Command line flag | ENV var and .env file value
-- | -- | -- | --
Profile | Default is default | --profile [value] | OKTA_AWSCLI_PROFILE
However, when using okta-aws-cli v2.1.2, this is the result you get when nothing is specified, despite a default profile being present:
```shell
$ okta-aws-cli web
Error: missing flags:
--org-domain
--oidc-client-id
```
This PR therefore sets the default value for the profile to be `default` as described in the documentation.
> Default value for profile argument should be the default profile

- README.md
SSO Token exchange step with 400 error since device registration is not detected during this step
> Added a note about mandatory `Device State = Any` policy setting

- internal/config/config.go
This PR is to fix the issue when you set the OKTA_AWSCLI_AWS_REGION via env var the region does not get saved in the profile. If we add the env var value to config here it gets saved as expected.
> fix: adds region from env var to config

- .github/workflows/release.yml
- CHANGELOG.md
- README.md
- go.mod
- go.sum
- internal/config/config.go
- internal/okta/application.go
- internal/paginator/paginator.go
- internal/webssoauth/webssoauth.go
Bringing in @pmgalea's bug fix for paginating apps. Also a better implementation of supporting non-Admin users. Set up as 2.2.0 release.
* Seamless support for non-Admin users if OIDC app has `okta.users.read.self` grant [#213](https://github.com/okta/okta-aws-cli/pull/213), thanks [@monde](https://github.com/monde)!
* Paginating more than 200 apps on `GET /api/v1/apps` not implemented [#212](https://github.com/okta/okta-aws-cli/pull/212), thanks [@pmgalea](https://github.com/pmgalea)!
> Paginate apps and better support for non-Admin users

- .github/workflows/release.yml
- .goreleaser.yaml
- go.mod
- go.sum
https://goreleaser.com/blog/goreleaser-v2/
https://goreleaser.com/customization/changelog/
Fixing https://github.com/okta/okta-aws-cli/actions/runs/9783071850/job/27010814665
```
Run goreleaser/goreleaser-action@v6.0.0
Warning: You are using 'latest' as default version. Will lock to '~> v2'.
Downloading https://github.com/goreleaser/goreleaser/releases/download/v2.0.1/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/166b5861-3334-4801-89a4-f4fbb61c3a17 -f /home/runner/work/_temp/c7[12](https://github.com/okta/okta-aws-cli/actions/runs/9783071850/job/27010814665#step:6:13)20f5-cdac-4d03-8ec9-b0b58ec6b9b6
GoReleaser latest installed successfully
/opt/hostedtoolcache/goreleaser-action/2.0.1/x64/goreleaser …
```
> Needed goreleaser adjustments.

- .github/workflows/chocolatey.yml
- nuspec/chocolatey/okta-aws-cli.nuspec
- nuspec/chocolatey/tools/chocolateyinstall.ps1
GH Action to publish to Chocolatey.org
> Publish to Chocolatey.org when a GH publish completes

- .gitignore
- CONTRIBUTING.md
- README.md
- cmd/root/profileslist/profiles-list.go
- cmd/root/root.go
- internal/config/config.go
- internal/output/aws_credentials_file.go
- internal/paginator/paginator.go
Bringing in @pmgalea's #222 `okta-aws-cli list-profiles`
> Bringing in @pmgalea's #222 `okta-aws-cli list-profiles`

- CHANGELOG.md
- Makefile
- cmd/root/root.go
- cmd/root/web/web.go
- internal/config/config.go
- internal/okta/apierror.go
- internal/paginator/paginator.go
- internal/webssoauth/webssoauth.go
Better retry for when the cached access token has been invalidated outside of `okta-aws-cli`'s control.
* Better retry for when the cached access token has been invalidated outside of okta-aws-cli's control
* Print a warning at first run if otka.yaml is malformed
*  Correct "default" profile flaw introduced in 2.2.0 release
*  Continue polling instead of exit on a 400 "slow_down" API error
* New command `okta-aws-cli list-profiles`
> Reset cached access token on `invalid_grant`

- cmd/root/web/web.go
- internal/okta/apierror.go
- internal/webssoauth/webssoauth.go
Getting rid of complicated and buggy retry logic.
Causes issue that surfaced in #228
Closes #228
> Fix buggy retry logic

- CHANGELOG.md
- internal/config/config.go
* Fix buggy retry error loop that causes operator confusion. [#237](https://github.com/okta/okta-aws-cli/pull/237), thanks [@monde](https://github.com/monde)!
* Clean up the non-admin user experience. [#235](https://github.com/okta/okta-aws-cli/pull/235), thanks [@monde](https://github.com/monde)!
* Don't warn if okta.yaml doesn't exist. [#232](https://github.com/okta/okta-aws-cli/pull/232), thanks [@monde](https://github.com/monde)!
* Correct Classic Org error and expected exit. [#231](https://github.com/okta/okta-aws-cli/pull/231), thanks [@monde](https://github.com/monde)!
> v2.3.1 Release

- internal/m2mauth/m2mauth.go
- test/fixtures/vcr/TestM2MAuthAccessToken.yaml
okta-aws-cli  is using the private_key_jwt client authentication method for requesting access_tokens from the POST /oauth2/v1/token endpoint in a non-standard way that is accepted by the POST /oauth2/v1/token endpoint.
It includes the client_assertion in the query string of the request instead of in the POST body. This is problematic because query strings should never contain sensitive data as they are prone to being logged.
The purpose of this PR is to move client_assertion from query string to POST body to avoid being logged
> fix client assertion not send through POST body

- go.mod
- go.sum
Update to latest aws-sdk-go package
https://github.com/aws/aws-sdk-go/releases/tag/v1.55.5
Closes #251
> Update to latest aws-sdk-go package

- cmd/root/web/web.go
Bringing in @Eitol's #241
This pull request addresses an issue where users with expired sessions in their browsers encounter repeated authentication failures when running the okta-aws-cli web command. Previously, the tool would attempt to authenticate twice and display an error message: "Cached access token appears to be stale...". However, it did not provide clear guidance on how to resolve the issue.
Updated the NewWebCommand function to check after two failed authentication attempts.
If the authentication fails due to an invalid_grant error after retries, the tool now informs the user to log out of Okta in their 
browser and log back in.
Added user-friendly messaging to guide users through resolving the expired session issue.
- Enhances user experience by providing clear instructions …
> Handle Okta authentication failures more gracefully

- README.md
- cmd/root/root.go
- go.sum
- internal/config/config.go
- internal/m2mauth/m2mauth.go
- internal/webssoauth/webssoauth.go
Toggle User-Agent in API calls to be simple "okta-aws-cli" with global flag `--short-user-agent`
Closes #248
> Toggle HTTP User-Agent in API calls to short form "okta-aws-cli"

- go.mod
- go.sum
- internal/m2mauth/m2mauth.go
Add JTI into okta claims to avoid it being reusable.
"If jti is specified, the token can only be used once. So, for example, subsequent token requests won't succeed."
https://developer.okta.com/docs/api/openapi/okta-oauth/guides/client-auth/
> update jti for claims

- README.md
Added note to README in the web command that AWS Fed app doesn't support device security posture.
Closes #65
> Note that AWS Fed app doesn't support device security posture

- README.md
- cmd/root/m2m/m2m.go
- internal/config/config.go
- internal/m2mauth/m2mauth.go
m2m allow STS role session name to be overridden with `--aws-sts-role-session-name [value]` CLI flag.
```
$ okta-aws-cli m2m --exec -- aws sts get-caller-identity
{
"UserId": "ABC:okta-aws-cli",
"Account": "123",
"Arn": "arn:aws:sts::123:assumed-role/myrole/okta-aws-cli"
}
```
```
$ okta-aws-cli m2m --aws-sts-role-session-name a-user --exec -- aws sts get-caller-identity
{
"UserId": "DEF:a-user",
"Account": "123",
"Arn": "arn:aws:sts::123:assumed-role/myrole/a-user"
}
```
Closes #165
> m2m allow STS role session name to be overridden 

- README.md
- cmd/root/root.go
- internal/config/config.go
Clarify difference between Okta access token expiry and AWS Session
Duration (expiry). Rename/deprecate CLI flag `--session-duration` to
`--aws-session-duration`.
Closes #181
Closes #246
> Rename/deprecate CLI flag `--session-duration` to `--aws-session-duration`

- CHANGELOG.md
- internal/config/config.go
* Multiple apps feature only requires `okta.users.read.self` scope [#254](https://github.com/okta/okta-aws-cli/pull/254), thanks [@monde](https://github.com/monde)!
* Toggle API HTTP User-Agent header to `okta-aws-cli` to ease use in a policy rule [#257](https://github.com/okta/okta-aws-cli/pull/257), thanks [@monde](https://github.com/monde)!
* Improve error message suggestion for expired token [#256](https://github.com/okta/okta-aws-cli/pull/256), thanks [@Eitol](https://github.com/Eitol)!
* JTI protection on m2m auth token [#259](https://github.com/okta/okta-aws-cli/pull/259), thanks [@duytiennguyen-okta](https://github.com/duytiennguyen-okta)!
* m2m allow STS role session name to be overridden [#262](https://github.com/okta/okta-aws-cli/pull/262), thanks …
> Prep 2.4.0 release

- CHANGELOG.md
- go.mod
- go.sum
- internal/config/config.go
- internal/m2mauth/m2mauth.go
- internal/okta/client_assertion_claims.go
- Bringing in curator's --aws-session-duration fix.
- https://github.com/okta/okta-aws-cli/pull/268
- https://github.com/okta/okta-aws-cli/pull/269
- Upgrade go-jose re: https://github.com/okta/okta-aws-cli/security/dependabot/9
Closes #268
Closes #269
Prep 2.4.1 release
> Release v2.4.1

- CHANGELOG.md
- README.md
- cmd/root/direct/direct.go
- cmd/root/root.go
- internal/aws/aws.go
- internal/config/config.go
- internal/directauth/directauth.go
- internal/m2mauth/m2mauth.go
- internal/okta/apierror.go
- internal/okta/challenge_token.go
- internal/okta/messages.go
- internal/okta/mfa_token.go
- internal/okta/okta.go
- internal/utils/utils.go
- internal/webssoauth/webssoauth.go
New `direct` command that implements out-of-bounds MFA [(Direct Authentication)](https://developer.okta.com/docs/guides/configure-direct-auth-grants/dmfaoobov/main/). OOB MFA combines the username/password grant with a push to Okta Verify for the second factor.
```shell
$ read -p "Okta Username: " myusername && read -s -p "Okta Password: " mypassword && echo
Okta Username: test@example.com
Okta Password:
$ okta-aws-cli direct \
--format noop \
--org-domain test.okta.com \
--oidc-client-id 0oa123 \
--authz-id aus456 \
--aws-iam-role arn:aws:iam::1234567890:role/my-role \
--username "${myusername}" \
--password "${mypassword}" \
--exec -- aws sts get-caller-identity
{
"UserId": "ZYZ789:okta-aws-cli",
"Account": "1234567890",
"Arn": "arn:aws:sts::1234567890:assumed-role/my-role"
}
```
> New `direct` command for Direct Authentication (out-of-bounds MFA)
